### ISSUE TITLE
train

### ISSUE THREAD

**Issue by ConanMusk** [zzy666666zzy/Non-Fusion-Network-for-3-D-Ranging#1]
Hello, is this code feasible? We are looking for the code "Non-Fusion Time-Resolved Depth Image Reconstruction using a Highly efficient Neural network Architecture".

**Comment by zzy666666zzy** [comment]
> Hello, is this code feasible? We are looking for the code "Non-Fusion Time-Resolved Depth Image Reconstruction using a Highly efficient Neural network Architecture".

**Comment by zzy666666zzy** [comment]
> 

The code in this repository is for the paper you wanted. The main idea of training is similar to "SINGLE-PHOTON 3D IMAGING WITH DEEP SENSOR FUSION." You can refer to that project and will understand this code.

**Comment by ConanMusk** [comment]
Thank you for your reply.
There are  folders named 'Q-UnetPP3D'  and the 'quanti_util', but I can't find them.
Could you please solve this problem?

![2022-01-22 21-16-24屏幕截图](https://user-images.githubusercontent.com/67884112/150640082-e75e47f1-4e1c-43eb-b774-0ed9aae4b68c.png)

![2022-01-22 21-14-33屏幕截图](https://user-images.githubusercontent.com/67884112/150640097-b93e8979-03ed-4b2b-af42-f2bf99bdb80f.png)

**Comment by ConanMusk** [comment]
Looking forward to your reply.

**Comment by zzy666666zzy** [comment]
> Thank you for your reply. There are folders named 'Q-UnetPP3D' and the 'quanti_util', but I can't find them. Could you please solve this problem?
> 
> ![2022-01-22 21-16-24屏幕截图](https://user-images.githubusercontent.com/67884112/150640082-e75e47f1-4e1c-43eb-b774-0ed9aae4b68c.png)
> 
> ![2022-01-22 21-14-33屏幕截图](https://user-images.githubusercontent.com/67884112/150640097-b93e8979-03ed-4b2b-af42-f2bf99bdb80f.png)

The model file is in the repository now, try it out.
